name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: push-main or release'
        required: true
        default: push-main
        options:
          - push-main
          - release
      tag_name:
        description: 'Release tag name (required for release)'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Tags
        id: tags
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.action }}" == "push-main" ]]; then
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.action }}" == "release" ]]; then
            echo "RELEASE_TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image for GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG || env.RELEASE_TAG }}

      - name: Build and Push Docker Image for Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wgdasboard:${{ env.LATEST_TAG || env.RELEASE_TAG }}
