name: Docker Image Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    # Step 2: Log in to Docker Hub with Docker Hub credentials
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # Step 3: Pull the image from GitHub Packages
    - name: Pull Docker Image from GitHub Packages
      run: |
        docker pull ghcr.io/shuricksumy/docker-wgdashboard:latest

    # Step 4: Run Docker Scout to scan the image
    - name: Analyze for critical and high CVEs
      uses: docker/scout-action@v1
      id: docker-scout-cves
      with:
        command: cves
        image: ghcr.io/shuricksumy/docker-wgdashboard:latest
        severity-cutoff: medium  # Adjust this as needed
        sarif-file: sarif.output.json
        summary: true

    - name: Upload SARIF result
      id: upload-sarif
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif.output.json
